baseURL = "https://261-25-005-web.github.io/"
languageCode = "en-us"
title = "Faisal Obied Prince"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
author = "Faisal Obied Prince"
description = "Computer Science Student | Machine Learning Enthusiast"

ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true

[params.profileMode]
enabled = true
title = "Hi, I'm Faisal Obied Prince 👋"
subtitle = "Computer Science Student | Machine Learning | Deep Learning | Web Developer"

buttons = [
  {name = "Projects", url = "/projects"},
  {name = "Blog", url = "/posts"},
  {name = "About", url = "/about"}
]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 3

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 4

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 5
